name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'
      - run: flutter --version

      - name: Install dependencies
        run: dart pub get
        
      - name: Install gen-l10n
        run: flutter gen-l10n

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: flutter test
